{
    "name": "mmb-config-client",
    "profiles": [
        "default"
    ],
    "label": "master",
    "version": "4d9240f45fecd34136f81683d44c2e144792af86",
    "propertySources": [
        {
            "name": "https://github.com/zhangting1/config/mmb-config-client.yml",
            "source": {
                "lucky-word": "mmb234"
            }
        }
    ]
}
